# Generated by Django 4.1.7 on 2024-06-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda_ou_aluguel', models.CharField(max_length=10)),
                ('design', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('localização', models.CharField(max_length=50)),
                ('tipologia', models.CharField(max_length=5)),
                ('moveis', models.CharField(max_length=1)),
                ('guardaFatos', models.CharField(max_length=1)),
                ('arCondicionado', models.CharField(max_length=1)),
                ('garagem', models.CharField(max_length=1)),
                ('cozinha', models.CharField(max_length=1)),
                ('americana', models.CharField(max_length=1)),
                ('numWC', models.IntegerField()),
                ('suite', models.CharField(max_length=1)),
                ('vista', models.CharField(max_length=1)),
                ('piscina', models.CharField(max_length=1)),
                ('obras', models.CharField(max_length=1)),
                ('preço', models.FloatField()),
            ],
        ),
    ]
