# Generated by Django 4.1.7 on 2024-06-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluator',
            old_name='americana',
            new_name='cozinhaAmericana',
        ),
        migrations.RemoveField(
            model_name='evaluator',
            name='cozinha',
        ),
    ]
