# Generated by Django 4.1.7 on 2024-06-08 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_rename_americana_evaluator_cozinhaamericana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
