# Generated by Django 4.1.7 on 2024-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_evaluator_created_at_alter_evaluator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bairro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('design', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipologia', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluator',
            name='localização',
        ),
    ]
