# Generated by Django 4.1.7 on 2024-06-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_bairro_design_tipologia_remove_evaluator_localização'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('cod_avaliação', models.AutoField(primary_key=True, serialize=False)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('cod_imovel', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venda_ou_aluguel', models.CharField(max_length=10)),
                ('design', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('tipologia', models.CharField(max_length=5)),
                ('moveis', models.CharField(max_length=1)),
                ('guardaFatos', models.CharField(max_length=1)),
                ('arCondicionado', models.CharField(max_length=1)),
                ('garagem', models.CharField(max_length=1)),
                ('cozinhaAmericana', models.CharField(max_length=1)),
                ('numWC', models.IntegerField()),
                ('suite', models.CharField(max_length=1)),
                ('vista', models.CharField(max_length=1)),
                ('piscina', models.CharField(max_length=1)),
                ('obras', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Evaluator',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='cod_imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.imovel'),
        ),
    ]
