# Generated by Django 4.1.7 on 2024-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0005_avaliacao_imovel_delete_evaluator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='numWC',
            field=models.PositiveIntegerField(),
        ),
    ]
